### PR TITLE
Sanitize

### PR DESCRIPTION
**Pull request by bobifle**
- Fix issue #7 
- add uuid, resource, reference capabilities to sanitize.py
- sanitize.py can now lower the case of object keys per EP2-Data requirement
- sanitizer run

### CODE REVIEW

**Comment by bobifle** [comment]
It just follows your first commandement "Lowercase keys on objects" :o)

But you're right the skill list may be reworked, ultimately, the skill name should match the name in skills.json so that app can relate them. I'll work something out...

**Comment by Arokha** [comment]
I'll 'array' the other skill lists in character creation stuff real quick.

**Comment by Arokha** [comment]
> If an app needs something Capitalized, then it should call Capitalize() on that object and should not rely on the json data initial format. No big deal though.

Unfortunately we can't store Capitalize() in the json, and things like "qe comms gear" won't get capitalized by generic title-case functions. So while I agree in most cases, there are some where it doesn't seem possible to indicate to everyone who would be using this data "Both the Q and the E should be caps" unless you want to get into the madness of storing functions that are eval'able in the data.

**Comment by bobifle** [comment]
Though I was not suggesting to pass case info through json, you have a point. Anyway I can lowercase everything in my app if I need to. So we're good :)Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Aronai Sieyes <notifications@github.com> 
Date : 06/09/2019  18:03  (GMT+01:00) 
À : Arokha/EP2-Data <EP2-Data@noreply.github.com> 
Cc : bobifle <sulay@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [Arokha/EP2-Data] Sanitize (#10) 


If an app needs something Capitalized, then it should call Capitalize() on that object and should not rely on the json data initial format. No big deal though.

Unfortunately we can't store Capitalize() in the json, and things like "qe comms gear" won't get capitalized by generic title-case functions. So while I agree in most cases, there are some where it doesn't seem possible to indicate to everyone who would be using this data "Both the Q and the E should be caps" unless you want to get into the madness of storing functions that are eval'able in the data.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Arokha/EP2-Data/pull/10?email_source=notifications\u0026email_token=AGLRSUVMPOA7LE5VJTLFVEDQIJ5MTA5CNFSM4ITSK5QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6DJNOI#issuecomment-528914105",
"url": "https://github.com/Arokha/EP2-Data/pull/10?email_source=notifications\u0026email_token=AGLRSUVMPOA7LE5VJTLFVEDQIJ5MTA5CNFSM4ITSK5QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6DJNOI#issuecomment-528914105",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
